authors:
  dooms:
    name: Dooms
    description: Hat master
    avatar: https://github.com/Doomsk.png
    url: https://github.com/Doomsk
  qinho:
    name: Inho
    description: Feutre hat
    avatar: https://github.com/q-inho.png
    url: https://github.com/q-inho
